package org.chzz.api.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;
import org.chzz.api.model.ProjectEntity;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("blog", "id", Blog.class);
		arp.addMapping("eo_project", "id", ProjectEntity.class);
	}
}

